version: "1.0"
stages:
  - prep
  - schedule deployments

steps:

  main_clone:
    title: Clone git repo
    type: git-clone
    stage: prep
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_BRANCH}}'

  build_docker_image:
    title: Build Codefresh CLI + Python image
    type: build
    stage: prep
    working_directory: '${{main_clone}}'
    dockerfile: Dockerfile
    image_name: 'codefresh-cli-py'
    tag: latest

  get_affected_combinations:
    title: Determine the needed deployments
    stage: schedule deployments
    image: alpine
    working_directory: '${{main_clone}}'
    commands:
      - cp example_deployment_schedule.yaml /codefresh/volume/deployment_schedule.yaml

  run_child_pipelines:
    title: Run child pipelines
    stage: schedule deployments
    image: ${{build_docker_image}}
    environment:
      - SCHEDULE_FILE=/codefresh/volume/deployment_schedule.yaml
      - DEPLOY_PIPELINE="ted-experiments/Terraform Plan and Apply"
      - DEPLOY_TRIGGER=called-by-scheduler
      - DEPLOY_BRANCH=${{CF_BRANCH}}
      # - LOG_LEVEL=DEBUG
    commands:
      - python3 cf_pipeline_scheduler.py
